### ISSUE TITLE
Sorry, where I can find the .csv file needed in the make_matadata.py

### ISSUE THREAD

**Issue by lbh111w** [CVRL/SiNC-rPPG#2]
Sorry, where I can find the .csv file needed in the make_matadata.py

**Comment by dalaoplan** [comment]
You only need to modify the ‘<path-to-preprocessed-PURE>’ to the folder where the data is saved after the first step of processing.

**Comment by Jemspeth** [comment]
Hi @lbh111w, @dalaoplan is correct. You set the desired path to the output .csv file as a command-line argument to the make_metadata.py script:
`python make_metadata.py <path-to-preprocessed-data> <path-to-output-csv>`
