### ISSUE TITLE
Experiment on UBFC cannot work

### ISSUE THREAD

**Issue by kevinlemon** [CVRL/SiNC-rPPG#3]
The UBFC.py is not finished.

    def __getitem__(self, idx):
        raise NotImplementedError
After preprocessing the UBFC-rPPG Dataset, run train.py with UBFC, there come errors as below:
 
File "../SiNC/src/datasets/UBFC.py", line 95, in set_augmentations
    raise NotImplementedError
NotImplementedError

**Comment by Jemspeth** [comment]
Hi @kevinlemon, I just pushed the UBFC dataloaders. They're effectively identical to PURE's apart from the `load_data` function. Let me know if you run into any issues.
